services:
    inkywhat-dsp-core:
        image: inkywhat-dsp/core
        container_name: inkywhat-dsp-core
        network_mode: host
        build:
            context: .
            dockerfile: ./build/core/Dockerfile
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
                - PIP_VERSION=${PIP_VERSION}
        volumes:
            - ..:/workspace:cached
            - $PWD/src:/src
            - $PWD/notebooks:/notebooks
            - $PWD/resources:/resources
        devices:
            - "/dev/i2c-1:/dev/i2c-1"
            - "/dev/spidev0.0:/dev/spidev0.0"
        env_file:
            - .env
            - .secrets/.env
        privileged: true

    inkywhat-dsp-api:
        image: inkywhat-dsp/api
        container_name: inkywhat-dsp-api
        network_mode: host
        build:
            context: .
            dockerfile: ./build/api/Dockerfile
        volumes:
            - ..:/workspace:cached
            - $PWD/src:/src
            - $PWD/resources:/resources
        devices:
            - "/dev/i2c-1:/dev/i2c-1"
            - "/dev/spidev0.0:/dev/spidev0.0"
        env_file:
            - .env
            - .secrets/.env
        privileged: true
        restart: unless-stopped
