services:
    inkywhat-dsp-core:
        image: inkywhat-dsp/core
        container_name: inkywhat-dsp-core
        build:
            context: .
            dockerfile: ./docker/core/Dockerfile
            args:
                - PYTHON_VERSION
                - UV_VERSION
                - UV_SYSTEM_PYTHON

    inkywhat-dsp-api:
        image: inkywhat-dsp/api
        container_name: inkywhat-dsp-api
        network_mode: host
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        volumes:
            - $PWD/resources:/resources
        devices:
            - "/dev/i2c-1:/dev/i2c-1"
            - "/dev/spidev0.0:/dev/spidev0.0"
        env_file:
            - .env
            - .secrets/.env
        privileged: true
        restart: unless-stopped
