services:
    inky-dsp-core:
        image: inky-dsp/core
        container_name: inky-dsp-core
        build:
            context: .
            dockerfile: ./docker/core/Dockerfile
        networks:
            - inky-dsp

    inky-dsp-api:
        image: inky-dsp/api
        container_name: inky-dsp-api
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        volumes:
            - $PWD/resources:/resources
        devices:
            - "/dev/i2c-1:/dev/i2c-1"
            - "/dev/spidev0.0:/dev/spidev0.0"
        env_file:
            - .env
        privileged: true
        restart: unless-stopped
        ports:
            - 8000:8000
        networks:
            - inky-dsp

networks:
    inky-dsp:
        name: inky-dsp
        driver: bridge
