services:
    inky-dsp-devcontainer:
        image: inky-dsp-devcontainer
        container_name: inky-dsp-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
            - ../resources:/resources
        devices:
            - "/dev/i2c-1:/dev/i2c-1"
            - "/dev/spidev0.0:/dev/spidev0.0"
        privileged: true
        env_file:
            - ../.env
        # This keeps the devcontainer running.
        entrypoint: ["tail", "-f", "/dev/null"]
        networks:
            - inky-dsp

networks:
    inky-dsp:
        name: inky-dsp
        driver: bridge

